# Header
menu:
  首页: /
  归档: /archives
  标签: /tags
  分类: /categories
  友链: /friends
  关于: /about

rss: /atom.xml
nav: right
mobile_nav: left



# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: left
widgets:
- userinfo
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Background
# background_image: /images/bg.jpeg
background_title: 图片来自网络

#Userinfo
author: 菩提思
slogan: 书到用时方恨少，事非经过不知难。
# avatar: /images/code-title.png
avatar_title: 图片来自网络

# Article code panel: cloud doorframe mac
highlightPanel: doorframe

#Gitment
gitment:
  owner: 
  repo: 
  client_id: 
  client_secret: 

# Miscellaneous
google_analytics:
gauges_analytics:
google_site_verification: 
baidu_site_verification: 
favicon: /images/default-avatar.jpeg
twitter:
google_plus:
fb_admins:
fb_app_id:
keywords:

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: false
  # enable: false
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-miku # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
    display:    # 模型展示的位置设置
        position: right     # 方位
        width: 80          # 宽度
        height: 160         # 高度
    mobile:
        show: true   # 在移动设备上是否开启live2d

